name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          # Ensure all dependencies are properly installed
          yarn list --pattern eslint
      - name: Verify ESLint installation
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "ESLint version: $(npx eslint --version)"
          echo "Checking if eslint is in node_modules..."
          ls -la node_modules/.bin/eslint || echo "ESLint not found in node_modules/.bin/"
          echo "Checking package.json scripts..."
          cat package.json | grep -A 5 -B 5 "lint"
      - name: Run ESLint
        run: |
          echo "Current working directory: $(pwd)"
          echo "Contents of current directory:"
          ls -la
          echo "Contents of node_modules/.bin:"
          ls -la node_modules/.bin/ | grep eslint || echo "No eslint in .bin"
          echo "Running ESLint..."
          # Try npm run lint first, fallback to npx if that fails
          npm run lint || npx eslint . --ext .vue,.js,.jsx,.ts,.tsx --fix
